In [2]:
import numpy as np

In [4]:
arr3d = np.random.randint(1,200,(5,10,6))
arr3d

array([[[  1,  54,  27,   3,  19, 118],
        [186, 160,  51,  80,  78,  66],
        [ 51, 157, 162,  63, 114, 139],
        [163,  57, 166, 152,  97, 148],
        [127,  99, 106, 182, 184, 171],
        [142,  28, 125, 168,   6, 199],
        [142, 187,  61, 130,  42,  38],
        [  3, 149, 152, 167,  89,  45],
        [143,  27,  94, 191, 139, 179],
        [ 68, 131, 185, 106,  96,  13]],

       [[169, 113, 127, 188,  11, 143],
        [ 62, 108,   4, 117,  71,  84],
        [166, 135, 155,  18, 118, 116],
        [  6, 113, 197,   1, 118,  50],
        [122,  40,  81, 189, 110, 170],
        [184, 126,  93,  23,  68,  94],
        [166, 134,  65,  69,  87, 186],
        [139,  13,  81, 176,  19,  11],
        [150, 135, 178,  94, 103,   9],
        [195,  28, 183,  68,  39,  25]],

       [[ 88, 107,  36, 151, 128, 132],
        [ 59,  48, 186, 183,  15,  89],
        [161, 130,  77, 132,  40,  22],
        [ 14, 100,  76, 123,  56, 196],
        [177,  53, 182,  36, 131, 18

In [6]:
arr3d.shape

(5, 10, 6)

In [8]:
arr3d.ndim

3

In [10]:
arr3d[0]

array([[  1,  54,  27,   3,  19, 118],
       [186, 160,  51,  80,  78,  66],
       [ 51, 157, 162,  63, 114, 139],
       [163,  57, 166, 152,  97, 148],
       [127,  99, 106, 182, 184, 171],
       [142,  28, 125, 168,   6, 199],
       [142, 187,  61, 130,  42,  38],
       [  3, 149, 152, 167,  89,  45],
       [143,  27,  94, 191, 139, 179],
       [ 68, 131, 185, 106,  96,  13]])

In [ ]:
#arr[row,column] = 2d
#arr[table,row,column] = 3d
#arr 3d = [s:s:j, s:s:j, s:s:j]

In [12]:
arr3d[0]

array([[  1,  54,  27,   3,  19, 118],
       [186, 160,  51,  80,  78,  66],
       [ 51, 157, 162,  63, 114, 139],
       [163,  57, 166, 152,  97, 148],
       [127,  99, 106, 182, 184, 171],
       [142,  28, 125, 168,   6, 199],
       [142, 187,  61, 130,  42,  38],
       [  3, 149, 152, 167,  89,  45],
       [143,  27,  94, 191, 139, 179],
       [ 68, 131, 185, 106,  96,  13]])

In [14]:
arr3d[-5]

array([[  1,  54,  27,   3,  19, 118],
       [186, 160,  51,  80,  78,  66],
       [ 51, 157, 162,  63, 114, 139],
       [163,  57, 166, 152,  97, 148],
       [127,  99, 106, 182, 184, 171],
       [142,  28, 125, 168,   6, 199],
       [142, 187,  61, 130,  42,  38],
       [  3, 149, 152, 167,  89,  45],
       [143,  27,  94, 191, 139, 179],
       [ 68, 131, 185, 106,  96,  13]])

In [16]:
arr3d[1,6:]

array([[166, 134,  65,  69,  87, 186],
       [139,  13,  81, 176,  19,  11],
       [150, 135, 178,  94, 103,   9],
       [195,  28, 183,  68,  39,  25]])

In [18]:
arr3d[0:5,6:]

array([[[142, 187,  61, 130,  42,  38],
        [  3, 149, 152, 167,  89,  45],
        [143,  27,  94, 191, 139, 179],
        [ 68, 131, 185, 106,  96,  13]],

       [[166, 134,  65,  69,  87, 186],
        [139,  13,  81, 176,  19,  11],
        [150, 135, 178,  94, 103,   9],
        [195,  28, 183,  68,  39,  25]],

       [[ 17,  55,  16, 119, 144,  96],
        [131, 163,  49,  42, 106,  80],
        [ 40,  36, 132,  29,  29, 193],
        [ 50,  46, 129, 158, 139,  69]],

       [[166,  76, 119, 182, 148, 167],
        [195, 157, 157, 135, 150,   3],
        [ 75,  92, 118, 177, 179,  36],
        [144,  24,  88, 132,  62,  29]],

       [[ 52,  90, 164,  55, 185, 157],
        [ 64, 148,  60, 187,  32, 119],
        [ 47,  82, 192,  85,  93,  43],
        [181,  70, 138, 180, 162,  97]]])

In [26]:
arr3d[0:5,-1:]

array([[[ 68, 131, 185, 106,  96,  13]],

       [[195,  28, 183,  68,  39,  25]],

       [[ 50,  46, 129, 158, 139,  69]],

       [[144,  24,  88, 132,  62,  29]],

       [[181,  70, 138, 180, 162,  97]]])

In [38]:
arr3d[4,-1:,-1] = 500
arr3d

array([[[  1,  54,  27,   3,  19, 118],
        [186, 160,  51,  80,  78,  66],
        [ 51, 157, 162,  63, 114, 139],
        [163,  57, 166, 152,  97, 148],
        [127,  99, 106, 182, 184, 171],
        [142,  28, 125, 168,   6, 199],
        [142, 187,  61, 130,  42,  38],
        [  3, 149, 152, 167,  89,  45],
        [143,  27,  94, 191, 139, 179],
        [ 68, 131, 185, 106,  96,  13]],

       [[169, 113, 127, 188,  11, 143],
        [ 62, 108,   4, 117,  71,  84],
        [166, 135, 155,  18, 118, 116],
        [  6, 113, 197,   1, 118,  50],
        [122,  40,  81, 189, 110, 170],
        [184, 126,  93,  23,  68,  94],
        [166, 134,  65,  69,  87, 186],
        [139,  13,  81, 176,  19,  11],
        [150, 135, 178,  94, 103,   9],
        [195,  28, 183,  68,  39,  25]],

       [[ 88, 107,  36, 151, 128, 132],
        [ 59,  48, 186, 183,  15,  89],
        [161, 130,  77, 132,  40,  22],
        [ 14, 100,  76, 123,  56, 196],
        [177,  53, 182,  36, 131, 18

In [40]:
arr3d[4,-1:,-1]

array([500])

In [46]:
arr = np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [48]:
arr.reshape(20,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [56]:
arr2 = arr.reshape(2,15,2)
arr2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39],
        [40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]]])

In [58]:
arr2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [60]:
arr2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [62]:
arr4 = np.random.randint(1,200,(5,3))
arr4

array([[ 86, 110,  69],
       [118, 140, 197],
       [159, 184,  49],
       [193,  52, 119],
       [  5, 143, 129]])

In [64]:
np.transpose(arr4)

array([[ 86, 118, 159, 193,   5],
       [110, 140, 184,  52, 143],
       [ 69, 197,  49, 119, 129]])

In [66]:
arr4.T

array([[ 86, 118, 159, 193,   5],
       [110, 140, 184,  52, 143],
       [ 69, 197,  49, 119, 129]])

In [70]:
arr4d = arr4.flatten()
arr4d

array([ 86, 110,  69, 118, 140, 197, 159, 184,  49, 193,  52, 119,   5,
       143, 129])

In [72]:
arr4d.max()

197

In [74]:
arr4d.min()

5

In [76]:
arr4d.mean()

116.86666666666666

In [80]:
np.median(arr4d)

119.0

In [82]:
arr5 = np.array([9,7,8])
arr5

array([9, 7, 8])

In [86]:
arr5.mean()

8.0

In [88]:
np.median(arr5)

8.0

In [90]:
arr5.argmin()

1

In [92]:
arr5.argmax()

0

In [100]:
arr5.sort()     #ascending order

In [102]:
arr5

array([7, 8, 9])

In [106]:
arr5[::-1]      #descending order

array([9, 8, 7])

In [108]:
arr5.argsort()

array([0, 1, 2], dtype=int64)