In [1]:
import numpy as np

In [19]:
lst=[[1,2,3],[4,5,6],[7,8,9]]
type(lst)

list

In [21]:
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr.ndim

2

In [25]:
arr[0]

array([1, 2, 3])

In [37]:
arr[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

arr[start:stop:jump--row, start:stop:jump--column]

In [41]:
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [43]:
arr2 = np.random.randint(1,200,(10,6))
arr2

array([[181,  39, 148, 159,  26, 182],
       [166,  14, 108, 119,  25, 113],
       [143,  73, 171, 117,  31,   8],
       [ 32, 131,  75, 100,   7,  78],
       [ 47, 155, 103,  53,  61, 118],
       [ 14,  11, 145,  39, 134, 198],
       [120,  67, 161, 115, 189,  32],
       [101, 142, 120,  10, 156, 178],
       [ 57,  61,   8, 170, 192,  40],
       [107,  17,  28,  12, 106,  36]])

In [45]:
arr2[4:9]

array([[ 47, 155, 103,  53,  61, 118],
       [ 14,  11, 145,  39, 134, 198],
       [120,  67, 161, 115, 189,  32],
       [101, 142, 120,  10, 156, 178],
       [ 57,  61,   8, 170, 192,  40]])

In [49]:
arr2[4:9,3:6]

array([[ 53,  61, 118],
       [ 39, 134, 198],
       [115, 189,  32],
       [ 10, 156, 178],
       [170, 192,  40]])

In [63]:
arr2[-6:-1,-3:]

array([[ 53,  61, 118],
       [ 39, 134, 198],
       [115, 189,  32],
       [ 10, 156, 178],
       [170, 192,  40]])

In [67]:
arr2[::-1]

array([[107,  17,  28,  12, 106,  36],
       [ 57,  61,   8, 170, 192,  40],
       [101, 142, 120,  10, 156, 178],
       [120,  67, 161, 115, 189,  32],
       [ 14,  11, 145,  39, 134, 198],
       [ 47, 155, 103,  53,  61, 118],
       [ 32, 131,  75, 100,   7,  78],
       [143,  73, 171, 117,  31,   8],
       [166,  14, 108, 119,  25, 113],
       [181,  39, 148, 159,  26, 182]])

In [69]:
arr2[::-1,::-1]

array([[ 36, 106,  12,  28,  17, 107],
       [ 40, 192, 170,   8,  61,  57],
       [178, 156,  10, 120, 142, 101],
       [ 32, 189, 115, 161,  67, 120],
       [198, 134,  39, 145,  11,  14],
       [118,  61,  53, 103, 155,  47],
       [ 78,   7, 100,  75, 131,  32],
       [  8,  31, 117, 171,  73, 143],
       [113,  25, 119, 108,  14, 166],
       [182,  26, 159, 148,  39, 181]])

In [75]:
arr2[5:7,0:2]

array([[ 14,  11],
       [120,  67]])

In [77]:
arr2

array([[181,  39, 148, 159,  26, 182],
       [166,  14, 108, 119,  25, 113],
       [143,  73, 171, 117,  31,   8],
       [ 32, 131,  75, 100,   7,  78],
       [ 47, 155, 103,  53,  61, 118],
       [ 14,  11, 145,  39, 134, 198],
       [120,  67, 161, 115, 189,  32],
       [101, 142, 120,  10, 156, 178],
       [ 57,  61,   8, 170, 192,  40],
       [107,  17,  28,  12, 106,  36]])

In [85]:
arr2[9:10,5:6]

array([[36]])

In [87]:
arr2[-1,-1] = 100

In [89]:
arr2[-1,-1]

100

In [95]:
arr2[0,3]

159

In [97]:
arr2[0,3] = 500

In [99]:
arr2 = np.random.randint(1,200,(3,4),(3,4),(3,4))
arr2

TypeError: randint() takes at most 4 positional arguments (5 given)